Repository noneandundefined/vision-ui, pull requests merged in 2025-02, with the labels that each got.

#34 added nginx configuration, tests and eslint
  .eslintignore
  .nginx/http.conf
  .nginx/nginx.conf
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  tsconfig.app.json
Labels: documentation, enhancement

#35 added base file - Protected for (auth)
  src/pages/Protected.tsx
Labels: enhancement

#42 added test for monitoring and <Index /> (#38)
  .husky/post-commit
  .husky/pre-commit
  config/config.ts
  dist/index.html
  dist/vision.bundle.js
  index.html
  package.json
  pnpm-lock.yaml
  preview/vision.bundle.js
  src/pages/Index.tsx
  src/services/monitoring.service.ts
  test/components/index-global.test.tsx
  test/components/monitoring.service.test.ts
  test/vitest.setup.ts
  tsconfig.app.json
  vite.config.ts
Labels: bug, new, dependencies

#46 added base hashing service class for password (#45)
  src/services/hash.service.ts
Labels: new

#60 added base-to-base authenticate (cookie (oauth)) (#48)
  README.md
  dist/index.html
  dist/vision.bundle.js
  dist/vision.css
  index.html
  package.json
  pnpm-lock.yaml
  preview/vision.bundle.js
  preview/vision.css
  src/App.tsx
  src/constants/svgs/lock-reset.tsx
  src/pages/Index.tsx
  src/pages/Protected.tsx
  src/services/auth.service.ts
  src/services/hash.service.ts
Labels: 🛠️ goal: fix, 📁 architecture, ⭐ goal: addition, 💻 aspect: code

#63 add hashing load to prevent brute force and change the hash algorithm…
  README.md
  dist/index.html
  dist/vision.bundle.js
  dist/vision.css
  index.html
  package.json
  pnpm-lock.yaml
  preview/vision.bundle.js
  preview/vision.css
  src/App.tsx
  src/constants/svgs/content-copy.tsx
  src/pages/Protected.tsx
  src/services/auth.service.ts
  src/services/hash.service.ts
  tailwind.config.js
Labels: 🛠️ goal: fix, ⭐ goal: addition, 💻 aspect: code
